name: CI Pipeline

on: [push]

jobs:
  test-and-lint:
    runs-on: ubuntu-latest

    env:
      NODE_VERSION: 18

    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}

      - name: Install dependencies
        run: make setup

      - name: Run tests
        run: make test

      - name: Run linter
        run: make lint
